system_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

supported_shell_types:
  - bash
  - zsh
supported_zsh_themes:
  - pure

shell_theme_pure:
  repo: "https://github.com/sindresorhus/pure.git"
  tag: "v1.23.0"

shell_binary: "{{ shell_set_default_shell | default('/bin/zsh' if ansible_system == 'Darwin' else '/bin/bash') }}"
shell_type: "{{ shell_binary.split('/')[-1] }}"
shell_theme: "{{ shell_set_theme | default() }}"
shell_extra_paths: "{{ shell_set_extra_paths | default([]) }}"

enable_fzf: "{{ shell_enable_fzf | default('false') | bool }}"
fzf_version: "{{ shell_fzf_version | default('0.62.0') }}"
fzf_tarball: "fzf-{{ fzf_version }}-{{ ansible_system | lower }}_{{ system_arch }}.tar.gz"
fzf_url: "https://github.com/junegunn/fzf/releases/download/v{{ fzf_version }}/{{ fzf_tarball }}"
