---
- name: Clone ZSH pure theme
  ansible.builtin.git:
    repo: "{{ shell_theme_pure.repo }}"
    dest: "{{ ansible_env.HOME }}/.zsh/theme/pure"
    version: "{{ shell_theme_pure.tag }}"

- name: Create ~/.zsh/theme-config
  ansible.builtin.copy:
    mode: "0644"
    dest: "{{ ansible_env.HOME }}/.zsh/theme-config.zsh"
    content: |
      # managed by ansible

      fpath+=($HOME/.zsh/theme/pure)
      autoload -U promptinit; promptinit
      prompt pure
