---
- name: Set shell profile
  ansible.builtin.template:
    mode: "0644"
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: Configure shell theme
  ansible.builtin.include_tasks: configure-theme-{{ shell_theme }}.yml
  when: shell_theme
